import { StyleSheet } from "react-native";
import { BottomTabInset, MaxContentWidth } from "@/constants/theme";

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F5F2EC" },
    safeArea: { flex: 1, width: "100%", maxWidth: MaxContentWidth, alignSelf: "center" },
    content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: BottomTabInset + 32 },
    header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 },
    pageHeader: { marginBottom: 28 },
    kicker: { color: "#8B877F", fontSize: 11, fontWeight: "700", letterSpacing: 1.5 },
    heading: { color: "#202522", fontSize: 34, fontWeight: "800", marginTop: 3 },
    datePill: { backgroundColor: "#E8E3DA", paddingHorizontal: 12, paddingVertical: 9, borderRadius: 20 },
    dateText: { color: "#716D65", fontSize: 10, fontWeight: "800", letterSpacing: 1 },
    childTabs: { flexDirection: "row", gap: 10, marginBottom: 20 },
    childTab: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        padding: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E3DED5",
    },
    childTabSelected: { backgroundColor: "#FFFDF9", borderColor: "#B8B1A6" },
    avatar: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" },
    avatarText: { color: "#FFFDF9", fontWeight: "800", fontSize: 16 },
    childDetails: { flex: 1, gap: 5 },
    childHours: { color: "#716D65", fontSize: 10, fontWeight: "800", fontVariant: ["tabular-nums"] },
    childName: { color: "#252A27", fontWeight: "800", fontSize: 15 },
    childRole: { color: "#938D84", fontSize: 10, marginTop: 2 },
    currentCard: { backgroundColor: "#252B28", borderRadius: 18, padding: 22, minHeight: 200, marginBottom: 26 },
    currentTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
    cardLabel: { color: "#A4AAA3", fontSize: 10, fontWeight: "800", letterSpacing: 1.2 },
    live: { flexDirection: "row", alignItems: "center", gap: 6 },
    liveDot: { backgroundColor: "#8FD49A", width: 7, height: 7, borderRadius: 4 },
    liveText: { color: "#8FD49A", fontSize: 10, fontWeight: "800", letterSpacing: 1 },
    activityName: { color: "#FFFDF9", fontSize: 28, fontWeight: "800", marginTop: 30 },
    elapsed: { color: "#FFFDF9", fontSize: 46, fontWeight: "300", marginTop: 3 },
    started: { color: "#A4AAA3", fontSize: 12, marginTop: 8 },
    sectionHeader: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", marginBottom: 12 },
    sectionTitle: { color: "#252A27", fontSize: 18, fontWeight: "800" },
    logFilter: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 11,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: "#D5D0C7",
        borderRadius: 8,
        backgroundColor: "#FFFDF9",
    },
    logFilterText: { color: "#5E5C56", fontSize: 11, fontWeight: "800" },
    logFilterChevron: { color: "#9A948A", fontSize: 13, fontWeight: "800" },
    logFilterMenu: {
        width: "100%",
        maxWidth: 420,
        alignSelf: "center",
        padding: 18,
        borderRadius: 16,
        backgroundColor: "#FFFDF9",
        shadowColor: "#202522",
        shadowOpacity: 0.2,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 8 },
        elevation: 8,
    },
    logFilterOption: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: "#EEEAE3",
    },
    logFilterOptionText: { flex: 1, color: "#5E5C56", fontSize: 14, fontWeight: "700" },
    logFilterCheck: { color: "#4B9B91", fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
    logFilterDot: { width: 10, height: 10, borderRadius: 5 },
    sectionHint: { color: "#9A948A", fontSize: 11 },
    exportActions: { flexDirection: "row", gap: 10, marginBottom: 16 },
    exportButton: {
        flex: 1,
        minHeight: 44,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        borderRadius: 8,
        backgroundColor: "#4B9B91",
    },
    exportButtonSecondary: { backgroundColor: "#FFFDF9", borderWidth: 1, borderColor: "#4B9B91" },
    exportButtonDisabled: { opacity: 0.45 },
    exportButtonText: { color: "#FFFDF9", fontSize: 12, fontWeight: "800" },
    exportButtonSecondaryText: { color: "#4B9B91" },
    boardIntro: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 12 },
    boardTotal: { color: "#716D65", fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
    board: { gap: 10, paddingBottom: 28 },
    activityColumn: { width: "100%" },
    activityHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        minHeight: 30,
        marginBottom: 7,
        paddingInline: 10,
    },
    activityTitle: { flex: 1, color: "#252A27", fontSize: 18, fontWeight: "800" },
    mergeActivityButton: { width: 30, height: 30, alignItems: "center", justifyContent: "center" },
    activityCount: { color: "#9A948A", fontSize: 11, fontWeight: "800" },
    activityGroup: {
        minHeight: 190,
        padding: 8,
        gap: 8,
    },
    activityGroupEmpty: { minHeight: 0, paddingVertical: 5 },
    childCard: {
        padding: 12,
        borderLeftWidth: 4,
        borderRadius: 9,
        backgroundColor: "#FFFDF9",
        shadowColor: "#252A27",
        shadowOpacity: 0.08,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
        elevation: 2,
    },
    childCardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6 },
    childCardName: { color: "#252A27", fontSize: 15, fontWeight: "800" },
    childCardTime: { fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
    childCardRole: { color: "#938D84", fontSize: 10, marginTop: 3 },
    childCardHours: { color: "#716D65", fontSize: 10, fontWeight: "800", fontVariant: ["tabular-nums"], marginTop: 8 },
    childCardStarted: { color: "#9A948A", fontSize: 10, marginTop: 11 },
    emptyColumn: { color: "#B0AAA0", fontSize: 11, textAlign: "center", marginTop: 68 },
    emptyColumnCompact: { marginTop: 0 },
    modalOverlay: { flex: 1, justifyContent: "center", padding: 20, backgroundColor: "#20252299" },
    activityMenu: {
        maxHeight: "90%",
        padding: 18,
        borderRadius: 16,
        backgroundColor: "#FFFDF9",
        shadowColor: "#202522",
        shadowOpacity: 0.2,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 8 },
        elevation: 8,
    },
    activityMenuTitle: { color: "#252A27", fontSize: 18, fontWeight: "800", marginBottom: 10 },
    activityOption: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: "#EEEAE3",
    },
    activityOptionLabels: { flex: 1, justifyContent: "center" },
    activityOptionText: { color: "#5E5C56", fontSize: 14, fontWeight: "700" },
    groupOptionText: { color: "#5E5C56", fontSize: 12, fontWeight: "500" },
    activityOptionCheck: { fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
    menuLabel: { color: "#9A948A", fontSize: 10, fontWeight: "800", letterSpacing: 1.1, marginTop: 12 },
    groupCard: {
        gap: 8,
        padding: 8,
        borderWidth: 1,
        borderStyle: "dashed",
        borderColor: "#D5D0C7",
        borderRadius: 10,
    },
    groupHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 4,
        minHeight: 28,
    },
    groupName: { flex: 1, flexShrink: 1, marginRight: 8, color: "#252A27", fontSize: 12, fontWeight: "800" },
    groupActivity: { fontSize: 10, fontWeight: "800" },
    categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 28 },
    categoryButton: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: "28%",
        minHeight: 58,
        paddingHorizontal: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E1DBD1",
        backgroundColor: "#FBF9F5",
        justifyContent: "center",
        gap: 7,
    },
    categoryProminent: {
        fontSize: 20,
        flexBasis: "46%",
    },
    categoryText: { color: "#6F6B63", fontSize: 12, fontWeight: "700" },
    categoryTextActive: { color: "#252A27" },
    check: { position: "absolute", right: 9, top: 9, fontSize: 13, fontWeight: "800" },
    totalsCard: { backgroundColor: "#FFFDF9", borderRadius: 14, paddingHorizontal: 16, marginBottom: 28 },
    totalRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#EEEAE3",
    },
    totalName: { flexDirection: "row", alignItems: "center", gap: 10 },
    totalLabel: { color: "#5E5C56", fontSize: 13, fontWeight: "600" },
    totalValue: { color: "#252A27", fontSize: 14, fontWeight: "800" },
    logCard: { backgroundColor: "#FFFDF9", borderRadius: 14, paddingHorizontal: 16, paddingVertical: 4 },
    logRow: {
        flexDirection: "row",
        alignItems: "center",
        minHeight: 46,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#EEEAE3",
    },
    logLine: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#D5D0C7" },
    logTime: { width: 65, color: "#9A948A", fontSize: 12, fontVariant: ["tabular-nums"] },
    logActivity: { color: "#6F6B63", fontSize: 13 },
    logActivityActive: { color: "#252A27", fontWeight: "800" },
    logChartCard: {
        backgroundColor: "#FFFDF9",
        borderRadius: 14,
        padding: 16,
        marginTop: 20,
        marginBottom: 28,
        overflow: "hidden",
    },
    logChartHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 12,
    },
    logChartLegend: { color: "#9A948A", fontSize: 10, fontWeight: "700" },
    logChart: { width: "100%", flexDirection: "row", alignItems: "flex-end", gap: 3, minHeight: 244 },
    logChartColumn: { flex: 1, flexBasis: 0, width: 0, alignItems: "center", gap: 6, minWidth: 0 },
    logChartValue: {
        color: "#716D65",
        fontSize: 9,
        fontWeight: "800",
        fontVariant: ["tabular-nums"],
        marginBottom: 4,
    },
    logChartTrack: {
        width: "100%",
        height: 220,
        justifyContent: "flex-end",
        backgroundColor: "#F1EDE6",
        borderRadius: 5,
        overflow: "hidden",
        position: "relative",
    },
    logChartBar: { position: "absolute", bottom: 0, left: 0, right: 0, borderRadius: 5, minHeight: 0 },
    logChartLimit: {
        position: "absolute",
        left: 0,
        right: 0,
        height: 2,
        backgroundColor: "#252A27",
    },
    logChartLimitLabel: {
        position: "absolute",
        left: 0,
        right: 0,
        color: "#252A27",
        fontSize: 8,
        fontWeight: "800",
        textAlign: "center",
        fontVariant: ["tabular-nums"],
    },
    logChartLabel: {
        width: "100%",
        color: "#6F6B63",
        fontSize: 9,
        fontWeight: "700",
        textAlign: "center",
        minHeight: 22,
    },
    pickerButton: {
        height: 56,
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 7,
        gap: 2,
        marginBottom: 6,
        borderWidth: 1.5,
        borderRadius: 8,
        backgroundColor: "#FBF9F5",
    },
    pickerButtonActive: { borderBottomColor: "transparent" },
    pickerLabelRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    pickerLabel: { fontSize: 10, fontWeight: "800" },
    pickerDuration: { fontSize: 9, fontWeight: "600" },
    activityTable: { flexDirection: "row", marginBottom: 20 },
    activityColumns: { flexDirection: "row", gap: 8 },
    childActivityColumn: { width: 112 },
    activityColumnHeader: {
        height: 52,
        justifyContent: "center",
        paddingHorizontal: 8,
    },
    activityColumnName: { color: "#252A27", fontSize: 13, fontWeight: "800" },
    activityColumnTimer: {
        height: 44,
        justifyContent: "center",
        alignItems: "center",
    },
    activityColumnTimerValue: { color: "#252A27", fontSize: 13, fontWeight: "800" },
    templateContainer: { flex: 1, justifyContent: "center", flexDirection: "row" },
    templateSafeArea: {
        flex: 1,
        paddingHorizontal: 16,
        alignItems: "center",
        gap: 12,
        paddingBottom: BottomTabInset + 12,
        maxWidth: MaxContentWidth,
    },
    templateHeroSection: { alignItems: "center", justifyContent: "center", flex: 1, paddingHorizontal: 16, gap: 16 },
    templateTitle: { textAlign: "center" },
    templateCode: { textTransform: "uppercase" },
    templateStepContainer: {
        gap: 12,
        alignSelf: "stretch",
        paddingHorizontal: 12,
        paddingVertical: 16,
        borderRadius: 16,
    },
    animatedIconImageContainer: { justifyContent: "center", alignItems: "center" },
    animatedIconGlow: { width: 201, height: 201, position: "absolute" },
    animatedIconContainer: { justifyContent: "center", alignItems: "center", width: 128, height: 128, zIndex: 100 },
    animatedIconImage: { width: 76, height: 71 },
    animatedIconBackground: {
        borderRadius: 40,
        experimental_backgroundImage: "linear-gradient(180deg, #3C9FFE, #0274DF)",
        width: 128,
        height: 128,
        position: "absolute",
    },
    splashOverlay: {
        ...StyleSheet.absoluteFill,
        backgroundColor: "#208AEF",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
    },
    webAnimatedIconContainer: { alignItems: "center", width: "100%", zIndex: 1000, position: "absolute", top: 202 },
    webAnimatedIconImage: { position: "absolute", width: 76, height: 71 },
    hintStepRow: { flexDirection: "row", justifyContent: "space-between" },
    hintCodeSnippet: { borderRadius: 8, paddingVertical: 2, paddingHorizontal: 8 },
    themedTextSmall: { fontSize: 14, lineHeight: 20, fontWeight: 500 },
    themedTextSmallBold: { fontSize: 14, lineHeight: 20, fontWeight: 700 },
    themedTextDefault: { fontSize: 16, lineHeight: 24, fontWeight: 500 },
    themedTextTitle: { fontSize: 48, fontWeight: 600, lineHeight: 52 },
    themedTextSubtitle: { fontSize: 32, lineHeight: 44, fontWeight: 600 },
    themedTextLink: { lineHeight: 30, fontSize: 14 },
    themedTextLinkPrimary: { lineHeight: 30, fontSize: 14, color: "#3c87f7" },
    themedTextCode: { fontSize: 12 },
    webBadgeContainer: { padding: 20, alignItems: "center", gap: 8 },
    webBadgeVersionText: { textAlign: "center" },
    webBadgeImage: { width: 123, aspectRatio: 123 / 24 },
    collapsibleHeading: { flexDirection: "row", alignItems: "center", gap: 8 },
    collapsiblePressedHeading: { opacity: 0.7 },
    collapsibleButton: { width: 16, height: 16, borderRadius: 12, justifyContent: "center", alignItems: "center" },
    collapsibleContent: { marginTop: 12, borderRadius: 12, marginLeft: 16, padding: 16 },
    exploreScrollView: { flex: 1 },
    exploreContentContainer: { flexDirection: "row", justifyContent: "center" },
    exploreContainer: { maxWidth: MaxContentWidth, flexGrow: 1 },
    exploreTitleContainer: { gap: 12, alignItems: "center", paddingHorizontal: 16, paddingVertical: 24 },
    exploreCenterText: { textAlign: "center" },
    exploreLinkButton: {
        flexDirection: "row",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        justifyContent: "center",
        gap: 4,
        alignItems: "center",
    },
    exploreSectionsWrapper: { gap: 20, paddingHorizontal: 16, paddingTop: 12 },
    exploreCollapsibleContent: { alignItems: "center" },
    exploreImageTutorial: { width: "100%", aspectRatio: 296 / 171, borderRadius: 12, marginTop: 8 },
    exploreImageReact: { width: 100, height: 100, alignSelf: "center" },
    tabsListContainer: {
        position: "absolute",
        width: "100%",
        padding: 12,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
    },
    tabsSlot: { flex: 1 },
    tabsInnerContainer: {
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 20,
        flexDirection: "row",
        alignItems: "center",
        flexGrow: 1,
        gap: 8,
        maxWidth: MaxContentWidth,
    },
    tabsBrandText: { marginRight: "auto" },
    tabsButtonView: { paddingVertical: 4, paddingHorizontal: 12, borderRadius: 12 },
    tabsExternalPressable: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 4,
        marginLeft: 12,
    },
    pressed: { opacity: 0.7 },
});

export default styles;
