import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { BottomTabInset, MaxContentWidth } from "@/constants/theme";

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F5F2EC" },
    safeArea: { flex: 1, width: "100%", maxWidth: MaxContentWidth, alignSelf: "center" },
    content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: BottomTabInset + 32 },
    header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 },
    pageHeader: { marginBottom: 28 },
    kicker: { color: "#8B877F", fontSize: 11, fontWeight: "700", letterSpacing: 1.5 },
    heading: { color: "#202522", fontSize: 34, fontWeight: "800", marginTop: 3 },
    datePill: { backgroundColor: "#E8E3DA", paddingHorizontal: 12, paddingVertical: 9, borderRadius: 20 },
    dateText: { color: "#716D65", fontSize: 10, fontWeight: "800", letterSpacing: 1 },
    childTabs: { flexDirection: "row", gap: 10, marginBottom: 20 },
    childTab: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        padding: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E3DED5",
    },
    childTabSelected: { backgroundColor: "#FFFDF9", borderColor: "#B8B1A6" },
    avatar: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" },
    avatarText: { color: "#FFFDF9", fontWeight: "800", fontSize: 16 },
    childDetails: { flex: 1, gap: 5 },
    childHours: { color: "#716D65", fontSize: 10, fontWeight: "800", fontVariant: ["tabular-nums"] },
    childName: { color: "#252A27", fontWeight: "800", fontSize: 15 },
    childRole: { color: "#938D84", fontSize: 10, marginTop: 2 },
    currentCard: { backgroundColor: "#252B28", borderRadius: 18, padding: 22, minHeight: 200, marginBottom: 26 },
    currentTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
    cardLabel: { color: "#A4AAA3", fontSize: 10, fontWeight: "800", letterSpacing: 1.2 },
    live: { flexDirection: "row", alignItems: "center", gap: 6 },
    liveDot: { backgroundColor: "#8FD49A", width: 7, height: 7, borderRadius: 4 },
    liveText: { color: "#8FD49A", fontSize: 10, fontWeight: "800", letterSpacing: 1 },
    activityName: { color: "#FFFDF9", fontSize: 28, fontWeight: "800", marginTop: 30 },
    elapsed: { color: "#FFFDF9", fontSize: 46, fontWeight: "300", marginTop: 3 },
    started: { color: "#A4AAA3", fontSize: 12, marginTop: 8 },
    sectionHeader: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", marginBottom: 12 },
    sectionTitle: { color: "#252A27", fontSize: 18, fontWeight: "800" },
    sectionHint: { color: "#9A948A", fontSize: 11 },
    boardIntro: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 12 },
    boardTotal: { color: "#716D65", fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
    board: { gap: 10, paddingBottom: 28 },
    activityColumn: { width: "100%" },
    activityHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        minHeight: 30,
        marginBottom: 7,
        paddingInline: 10,
    },
    activityTitle: { flex: 1, color: "#252A27", fontSize: 18, fontWeight: "800" },
    mergeActivityButton: { width: 30, height: 30, alignItems: "center", justifyContent: "center" },
    activityCount: { color: "#9A948A", fontSize: 11, fontWeight: "800" },
    activityGroup: {
        minHeight: 190,
        padding: 8,
        gap: 8,
    },
    activityGroupEmpty: { minHeight: 0, paddingVertical: 5 },
    childCard: {
        padding: 12,
        borderLeftWidth: 4,
        borderRadius: 9,
        backgroundColor: "#FFFDF9",
        shadowColor: "#252A27",
        shadowOpacity: 0.08,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
        elevation: 2,
    },
    childCardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6 },
    childCardName: { color: "#252A27", fontSize: 15, fontWeight: "800" },
    childCardTime: { fontSize: 11, fontWeight: "800", fontVariant: ["tabular-nums"] },
    childCardRole: { color: "#938D84", fontSize: 10, marginTop: 3 },
    childCardHours: { color: "#716D65", fontSize: 10, fontWeight: "800", fontVariant: ["tabular-nums"], marginTop: 8 },
    childCardStarted: { color: "#9A948A", fontSize: 10, marginTop: 11 },
    emptyColumn: { color: "#B0AAA0", fontSize: 11, textAlign: "center", marginTop: 68 },
    emptyColumnCompact: { marginTop: 0 },
    modalOverlay: { flex: 1, justifyContent: "center", padding: 20, backgroundColor: "#20252299" },
    activityMenu: {
        maxHeight: "90%",
        padding: 18,
        borderRadius: 16,
        backgroundColor: "#FFFDF9",
        shadowColor: "#202522",
        shadowOpacity: 0.2,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 8 },
        elevation: 8,
    },
    activityMenuTitle: { color: "#252A27", fontSize: 18, fontWeight: "800", marginBottom: 10 },
    activityOption: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: "#EEEAE3",
    },
    activityOptionText: { flex: 1, color: "#5E5C56", fontSize: 14, fontWeight: "700" },
    activityOptionCheck: { fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
    menuLabel: { color: "#9A948A", fontSize: 10, fontWeight: "800", letterSpacing: 1.1, marginTop: 12 },
    groupCard: {
        gap: 8,
        padding: 8,
        borderWidth: 1,
        borderStyle: "dashed",
        borderColor: "#D5D0C7",
        borderRadius: 10,
    },
    groupHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 4,
        minHeight: 28,
    },
    groupName: { flex: 1, flexShrink: 1, marginRight: 8, color: "#252A27", fontSize: 12, fontWeight: "800" },
    groupActivity: { fontSize: 10, fontWeight: "800" },
    categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 28 },
    categoryButton: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: "28%",
        minHeight: 58,
        paddingHorizontal: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E1DBD1",
        backgroundColor: "#FBF9F5",
        justifyContent: "center",
        gap: 7,
    },
    categoryProminent: {
        fontSize: 20,
        flexBasis: "46%",
    },
    categoryDot: { width: 12, height: 12, borderRadius: 8 },
    categoryText: { color: "#6F6B63", fontSize: 12, fontWeight: "700" },
    categoryTextActive: { color: "#252A27" },
    check: { position: "absolute", right: 9, top: 9, fontSize: 13, fontWeight: "800" },
    totalsCard: { backgroundColor: "#FFFDF9", borderRadius: 14, paddingHorizontal: 16, marginBottom: 28 },
    totalRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#EEEAE3",
    },
    totalName: { flexDirection: "row", alignItems: "center", gap: 10 },
    totalLabel: { color: "#5E5C56", fontSize: 13, fontWeight: "600" },
    totalValue: { color: "#252A27", fontSize: 14, fontWeight: "800" },
    logCard: { backgroundColor: "#FFFDF9", borderRadius: 14, paddingHorizontal: 16, paddingVertical: 4 },
    logRow: {
        flexDirection: "row",
        alignItems: "center",
        minHeight: 46,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#EEEAE3",
    },
    logLine: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#D5D0C7" },
    logTime: { width: 48, color: "#9A948A", fontSize: 12, fontVariant: ["tabular-nums"] },
    logActivity: { color: "#6F6B63", fontSize: 13 },
    logActivityActive: { color: "#252A27", fontWeight: "800" },
    pressed: { opacity: 0.7 },
});

export default styles;
