#!/usr/bin/env sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "main" ]; then
  echo "🚫 Error: Direct commits to the 'main' branch are not allowed."
  echo "Please create a new branch, commit there, and open a Pull Request."
  exit 1
fi

npm run validate